---
- name: Configure git user name
  git_config:
    name: user.name
    value: "{{ git_user_name }}"
    scope: global
  tags:
    - git
    - config

- name: Configure git user email
  git_config:
    name: user.email
    value: "{{ git_user_email }}"
    scope: global
  tags:
    - git
    - config

- name: Configure git global settings
  git_config:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    scope: global
  loop: "{{ git_global_config }}"
  tags:
    - git
    - config